import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "@rainbow-me/rainbowkit/styles.css";
import "./globals.css";
import { ChainProviders } from "@/components/Providers";
import { NextUIProvider } from "@nextui-org/react";
import { Navbar } from "@/components/Navbar";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <ChainProviders>
          <NextUIProvider>
            <Navbar />
            {children}
          </NextUIProvider>
        </ChainProviders>
      </body>
    </html>
  );
}
